version: '3'

services:

    redis:
        image: redis

    postgres:
        image: postgres
        restart: always
        environment:
            - DB_USERNAME=postgres
            - DB_PASSWORD=qwerty

    frontend:
        image: frontend
        build: frontend-example-docker
        ports:
            - 5000:5000

    backend:
        image: backend
        build: backend-example-docker
        ports:
            - 8000:8000
        volumes:
            - ./backend-example-docker/logs.txt:/app/logs.txt
        environment:
            - REDIS=redis
            - DB_NAME=postgres
            - DB_HOST=postgres
            - DB_USERNAME=postgres
            - DB_PASSWORD=qwerty