version: '3'

services:
    training:
        image: ml-training
        volumes:
            - training:/src/imgs
            - training:/src/data
            - training:/src/model

    frontend:
        image: ml-frontend
        ports:
            - 3000:3000

    backend:
        image: ml-backend
        ports:
            - 5000:5000
        volumes:
            - training:/src/model

volumes:
    training: